version: '3.8'
services:
  app:
    build: .
    container_name: uptime-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      PORT: 3000
      MYSQL_DSN: ${MYSQL_DSN}
      UPTIME_API_KEY: ${UPTIME_API_KEY}
